In [1]:
import pandas as pd

In [5]:
df = pd.read_xml('complex_xml_structures.xml')
df

  name      city
0  USA  \n

In [10]:
df = pd.read_xml('complex_xml_structures.xml',xpath='//city')  ## person data into city column
df

       name  person
0  New York     NaN

In [21]:
namespace = {'ns':"http://www.example.com"}
df2 = pd.read_xml('xml_namespace.xml' , namespaces=namespace , xpath='//ns:person') # if there is a namespace in data , you have to define it first
df2

   name  age
0  John   30
1  Anna   25
2  Johi   30
3  Annu   25

In [25]:
foo = 'John'
df2.query("name == @foo")

   name  age
0  John   30

In [26]:
dft = pd.DataFrame({'time':['2022-09-14 00:52:00-07:00','2020-09-14 00:52:30-07:00'],'letter':['A','B']})
dft['time'] = pd.to_datetime(dft.time)

In [ ]:
dft

                       time letter
0 2022-09-14 00:52:00-07:00      A
1 2020-09-14 00:52:30-07:00      B

: